<?php
/*
 * Copyright (c) 2020 Zengliwei
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE AUTHORS
 * OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

use Common\Blog\Block\Post\Grid;

/* @var Grid $block */
$posts = $block->getPostCollection();
?>
<div class="block block-blog-post-list">
    <div class="block-content">
        <div class="posts">
            <?php if (count($posts)): ?>
                <?php foreach ($posts as $post) : ?>
                    <div class="post">
                        <?php if ($post->getImage()) : ?>
                            <div class="post-image">
                                <a href="<?= $block->escapeHtmlAttr($block->getPostUrl($post)); ?>">
                                    <img alt="<?= $block->escapeHtmlAttr($post->getTitle()) ?>"
                                         src="<?= $block->escapeHtmlAttr($block->getMediaUrl($post->getImage())) ?>"/>
                                </a>
                            </div>
                        <?php endif; ?>
                        <div class="post-title">
                            <h3><a href="<?= $block->escapeHtmlAttr($block->getPostUrl($post)); ?>">
                                    <?= $block->escapeHtml($post->getTitle()) ?>
                                </a></h3>
                        </div>
                        <div class="post-info">
                            <div class="comments">
                                <?= $block->escapeHtml(__('%1 Comments', $block->getComments($post->getId()))) ?>
                            </div>
                            <div class="date">
                                <?= $block->escapeHtml($block->formatDateTime($post->getCreatedAt())) ?>
                            </div>
                        </div>
                        <?php if ($post->getSummary()) : ?>
                            <div class="post-summary">
                                <?= $block->escapeHtml($post->getSummary()) ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="no-item"><?= __('No matched record.') ?></p>
            <?php endif; ?>
        </div>
        <?= $this->getChildHtml('blog_post_pager'); ?>
    </div>
</div>
