<?php
/*
 * Copyright (c) 2020 Zengliwei
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE AUTHORS
 * OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

use Common\Blog\Block\Widget\Tags;
use Common\Blog\Model\Post\Tag;

/* @var Tags $block */
$tags = $block->getTagCollection();
?>
<div class="block block-blog-tags">
    <div class="block-title">
        <h3><?= __('Blog Tags') ?></h3>
    </div>
    <div class="block-content">
        <?php foreach ($tags as $tag): ?>
            <div class="blog-tag">
                <a href="<?= $block->escapeHtmlAttr($block->getTagUrl($tag)) ?>">
                    <span><?= $block->escapeHtml($tag->getData(Tag::FIELD_NAME)) ?></span>
                </a>
                <span class="posts">(<?= $block->escapeHtml($tag->getData('posts')) ?>)</span>
            </div>
        <?php endforeach; ?>
    </div>
</div>
