<?php
/*
 * Copyright (c) 2020 Zengliwei
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE AUTHORS
 * OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

use Common\Blog\Model\Post\Comment;
use Magento\Framework\View\Element\Template;

/* @var Template $block */
/* @var Comment $comment */
$comment = $block->getData('comment');
?>
<div class="comment">
    <div class="info">
        <div class="date"><?= $comment->getData(Comment::FIELD_CREATED_AT) ?></div>
        <div class="author"><?= $comment->getData(Comment::FIELD_CUSTOMER_ID) ?></div>
    </div>
    <div class="content"><?= $comment->getData(Comment::FIELD_CONTENT) ?></div>
    <div class="replies">
        <?= $block->getData('replies_html') ?>
    </div>
    <?= $block->getData('reply_form_html') ?>
</div>
